/**
 * The emails' words in the seven languages beside English (the English and
 * the layout are in `emails.ts`).
 *
 * EVERY LANGUAGE HERE IS AN UNREVIEWED DRAFT until a native speaker has read
 * it (the release waits for that review). `{{…}}` are the outbox's variables,
 * left exactly as they are; a date and a time are formatted by Adminium in the
 * guest's language.
 */
import type { EmailWords } from "./emails.ts";

/** One language's words, from the sentences each email shares. */
function words(
  shared: Pick<EmailWords, "reference" | "theRoom" | "total" | "settle" | "cancelBy" | "lateOrEarly" | "totalWas" | "taxLine" | "paid" | "balanceLine" | "attached" | "foot">,
  s: {
    madeName: string;
    madeDeskName: string;
    madeSubject: string;
    madePre: string;
    madeDeskPre: string;
    madeHeading: string;
    madePara: string;
    button: string;
    cancelledSubject: string;
    nothing: string;
    cancelledHeading: string;
    stillOpen: string;
    selfLate: string;
    desk: string;
    deskLate: string;
    names: { self: string; selfLate: string; desk: string; deskLate: string; house: string; noShow: string };
    houseSubject: string;
    housePre: string;
    houseHeading: string;
    housePara: string;
    houseRing: string;
    noShowSubject: string;
    noShowHeading: string;
    noShowPara: string;
    noShowRing: string;
    datesName: string;
    datesSubject: string;
    datesPre: string;
    datesHeading: string;
    datesBefore: string;
    datesNow: string;
    linkName: string;
    linkSubject: string;
    linkPre: string;
    linkHeading: string;
    linkPara: string;
    linkRing: string;
    folioName: string;
    folioSubject: string;
    folioPre: string;
    folioHeading: string;
    folioPara: string;
    soFarName: string;
    soFarSubject: string;
    soFarPre: string;
    soFarHeading: string;
    soFarPara: string;
  },
): EmailWords {
  const cancelled = (name: string, paras: string[]) => ({ name, subject: s.cancelledSubject, preheader: s.nothing.replace(/[.。]$/, ""), heading: s.cancelledHeading, paras });
  return {
    ...shared,
    "stay-made": { name: s.madeName, subject: s.madeSubject, preheader: s.madePre, heading: s.madeHeading, paras: [s.madePara], button: s.button },
    "stay-made-desk": { name: s.madeDeskName, subject: s.madeSubject, preheader: s.madeDeskPre, heading: s.madeHeading, paras: [s.madePara] },
    "stay-cancelled-self": cancelled(s.names.self, [s.nothing, s.stillOpen]),
    "stay-cancelled-self-late": cancelled(s.names.selfLate, [s.selfLate, s.stillOpen]),
    "stay-cancelled-desk": cancelled(s.names.desk, [s.desk, s.stillOpen]),
    "stay-cancelled-desk-late": cancelled(s.names.deskLate, [s.deskLate, s.stillOpen]),
    "stay-cancelled-house": { name: s.names.house, subject: s.houseSubject, preheader: s.housePre, heading: s.houseHeading, paras: [s.housePara, s.houseRing] },
    "stay-no-show": { name: s.names.noShow, subject: s.noShowSubject, preheader: s.nothing.replace(/[.。]$/, ""), heading: s.noShowHeading, paras: [s.noShowPara, s.noShowRing] },
    "stay-dates-changed": { name: s.datesName, subject: s.datesSubject, preheader: s.datesPre, heading: s.datesHeading, paras: [s.datesBefore, s.datesNow] },
    "stay-new-link": { name: s.linkName, subject: s.linkSubject, preheader: s.linkPre, heading: s.linkHeading, paras: [s.linkPara, s.linkRing], button: s.button },
    "stay-folio": { name: s.folioName, subject: s.folioSubject, preheader: s.folioPre, heading: s.folioHeading, paras: [s.folioPara] },
    "stay-folio-owing": { name: s.soFarName, subject: s.soFarSubject, preheader: s.soFarPre, heading: s.soFarHeading, paras: [s.soFarPara] },
  };
}

const FOOT = "{{appName}} · {{practice.address}} · {{practice.phone}} · {{practice.email}}.";

export const EMAIL_DE = words(
  {
    reference: "Ihre Referenz",
    theRoom: "{{room_type.name}}, {{stay.arrive.day_month}} bis {{stay.depart.day_month}}",
    total: "Gesamt",
    settle: "Online wird nichts abgebucht. Sie begleichen alles an der Rezeption.",
    cancelBy: "Eine Stornierung kostet nichts. Nach {{stay.cancel_by.time}} am {{stay.cancel_by.date}} wird sie als verspätet vermerkt.",
    lateOrEarly: "Später oder früher? Schreiben Sie an {{practice.email}} oder rufen Sie uns an: {{practice.phone}}.",
    totalWas: "Gesamt, vorher {{was.total.money}}",
    taxLine: "{{stay.tax_label}} ({{stay.tax_rate.percent}})",
    paid: "Bezahlt",
    balanceLine: "Noch offen",
    attached: "Ihre Gastrechnung für {{room_type.name}}, {{stay.arrive.day_month}} bis {{stay.depart.day_month}}, liegt bei.",
    foot: `${FOOT} Sie erhalten diese E-Mail, weil Sie bei uns ein Zimmer reserviert haben.`,
  },
  {
    madeName: "Reservierung eingegangen",
    madeDeskName: "Reservierung an der Rezeption",
    madeSubject: "Ihr Zimmer bei {{appName}}, {{stay.ref}}",
    madePre: "{{stay.arrive.day_month}} bis {{stay.depart.day_month}} · {{stay.total.money}} · online wird nichts abgebucht",
    madeDeskPre: "{{stay.arrive.day_month}} bis {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "Ihr Zimmer ist reserviert, {{recipient.first_name}}.",
    madePara: "Anreise am {{stay.arrive.day_month}} ab {{practice.arrive_from.time}}. Abreise am {{stay.depart.day_month}} bis {{practice.leave_by.time}}.",
    button: "Ihre Reservierung ansehen",
    cancelledSubject: "Ihre Reservierung {{stay.ref}} ist storniert",
    nothing: "Es wird nichts berechnet.",
    cancelledHeading: "Ihre Reservierung ist storniert.",
    stillOpen: "Wenn Sie nicht stornieren wollten, schreiben Sie an {{practice.email}} oder rufen Sie uns an: {{practice.phone}} – wir sehen nach, was noch zu haben ist.",
    selfLate: "Sie haben nach {{stay.cancel_by.time}} am {{stay.cancel_by.date}} storniert, daher gilt dies als späte Stornierung. Es wird nichts berechnet.",
    desk: "Wie gewünscht haben wir sie storniert. Es wird nichts berechnet.",
    deskLate: "Wie gewünscht haben wir sie storniert. Das war nach {{stay.cancel_by.time}} am {{stay.cancel_by.date}}, daher gilt dies als späte Stornierung. Es wird nichts berechnet.",
    names: {
      self: "Vom Gast storniert",
      selfLate: "Vom Gast spät storniert",
      desk: "Auf Wunsch des Gastes storniert",
      deskLate: "Auf Wunsch des Gastes spät storniert",
      house: "Vom Haus storniert",
      noShow: "Wir haben Sie vermisst",
    },
    houseSubject: "Wir mussten {{stay.ref}} stornieren",
    housePre: "Es tut uns sehr leid · es wird nichts berechnet",
    houseHeading: "Es tut uns sehr leid, {{recipient.first_name}}.",
    housePara: "Wir mussten Ihre Reservierung {{stay.ref}} ({{room_type.name}}, {{stay.arrive.day_month}} bis {{stay.depart.day_month}}) stornieren. Es tut uns sehr leid. Es wird nichts berechnet.",
    houseRing: "Rufen Sie uns an unter {{practice.phone}}, und wir helfen Ihnen, ein anderes Zimmer zu finden.",
    noShowSubject: "Wir haben Sie vermisst – {{stay.ref}}",
    noShowHeading: "Wir haben Sie vermisst, {{recipient.first_name}}.",
    noShowPara: "Wir haben Ihr Zimmer für den {{stay.arrive.day_month}} gehalten, aber Sie sind nicht angekommen. Daher ist die Reservierung {{stay.ref}} als nicht erschienen markiert. Es wird nichts berechnet.",
    noShowRing: "Wenn Sie noch unterwegs sind, rufen Sie uns an: {{practice.phone}}.",
    datesName: "Daten geändert",
    datesSubject: "Ihre Reisedaten wurden geändert – {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} bis {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "Ihre Reisedaten wurden geändert, {{recipient.first_name}}.",
    datesBefore: "Vorher: {{was.arrive.day_month}} bis {{was.depart.day_month}}.",
    datesNow: "Jetzt: {{stay.arrive.day_month}} bis {{stay.depart.day_month}}. Ihre Extras gelten für die neuen Daten.",
    linkName: "Ein neuer Link",
    linkSubject: "Ein neuer Link zu Ihrer Reservierung {{stay.ref}}",
    linkPre: "Der alte Link öffnet sie nicht mehr",
    linkHeading: "Hier ist Ihr neuer Link, {{recipient.first_name}}.",
    linkPara: "Sie haben einen neuen Link zu Ihrer Reservierung angefordert. Der Link, den wir Ihnen vorher geschickt haben, öffnet sie nicht mehr.",
    linkRing: "Wenn Sie ihn nicht angefordert haben, rufen Sie uns an: {{practice.phone}}.",
    folioName: "Die Gastrechnung",
    folioSubject: "Ihre Gastrechnung von {{appName}} – {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} bis {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "Danke für Ihren Aufenthalt, {{recipient.first_name}}.",
    folioPara: "Wir hoffen, Sie bald wiederzusehen.",
    soFarName: "Die Zwischenrechnung",
    soFarSubject: "Ihre Zwischenrechnung – {{stay.ref}}",
    soFarPre: "{{stay.balance.money}} noch offen",
    soFarHeading: "Ihre Zwischenrechnung, {{recipient.first_name}}.",
    soFarPara: "An der Rezeption sind noch {{stay.balance.money}} zu begleichen.",
  },
);

export const EMAIL_FR = words(
  {
    reference: "Votre référence",
    theRoom: "{{room_type.name}}, du {{stay.arrive.day_month}} au {{stay.depart.day_month}}",
    total: "Total",
    settle: "Rien n'est prélevé en ligne. Vous réglez à la réception.",
    cancelBy: "Annuler ne coûte rien. Après {{stay.cancel_by.time}} le {{stay.cancel_by.date}}, une annulation est notée comme tardive.",
    lateOrEarly: "En retard ou en avance ? Écrivez à {{practice.email}} ou appelez-nous au {{practice.phone}}.",
    totalWas: "Total, auparavant {{was.total.money}}",
    taxLine: "{{stay.tax_label}} ({{stay.tax_rate.percent}})",
    paid: "Payé",
    balanceLine: "Reste à régler",
    attached: "Votre note du séjour pour {{room_type.name}}, du {{stay.arrive.day_month}} au {{stay.depart.day_month}}, est jointe.",
    foot: `${FOOT} Vous recevez cet e-mail parce que vous avez réservé une chambre chez nous.`,
  },
  {
    madeName: "Réservation effectuée",
    madeDeskName: "Réservation faite à la réception",
    madeSubject: "Votre chambre à {{appName}}, {{stay.ref}}",
    madePre: "Du {{stay.arrive.day_month}} au {{stay.depart.day_month}} · {{stay.total.money}} · rien n'est prélevé en ligne",
    madeDeskPre: "Du {{stay.arrive.day_month}} au {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "Votre chambre est réservée, {{recipient.first_name}}.",
    madePara: "Arrivée le {{stay.arrive.day_month}} à partir de {{practice.arrive_from.time}}. Départ le {{stay.depart.day_month}} avant {{practice.leave_by.time}}.",
    button: "Voir votre réservation",
    cancelledSubject: "Votre réservation {{stay.ref}} est annulée",
    nothing: "Vous ne payez rien.",
    cancelledHeading: "Votre réservation est annulée.",
    stillOpen: "Si vous ne vouliez pas annuler, écrivez à {{practice.email}} ou appelez-nous au {{practice.phone}} : nous verrons ce qui reste disponible.",
    selfLate: "Vous avez annulé après {{stay.cancel_by.time}} le {{stay.cancel_by.date}} : l'annulation est donc marquée comme tardive. Vous ne payez rien.",
    desk: "Comme vous l'avez demandé, nous l'avons annulée. Vous ne payez rien.",
    deskLate: "Comme vous l'avez demandé, nous l'avons annulée. C'était après {{stay.cancel_by.time}} le {{stay.cancel_by.date}} : l'annulation est donc marquée comme tardive. Vous ne payez rien.",
    names: {
      self: "Annulé par le client",
      selfLate: "Annulé tardivement par le client",
      desk: "Annulé à la demande du client",
      deskLate: "Annulé tardivement à la demande du client",
      house: "Annulé par l'hôtel",
      noShow: "Nous vous attendions",
    },
    houseSubject: "Nous avons dû annuler {{stay.ref}}",
    housePre: "Toutes nos excuses · vous ne payez rien",
    houseHeading: "Toutes nos excuses, {{recipient.first_name}}.",
    housePara: "Nous avons dû annuler votre réservation {{stay.ref}} ({{room_type.name}}, du {{stay.arrive.day_month}} au {{stay.depart.day_month}}). Nous en sommes vraiment désolés. Vous ne payez rien.",
    houseRing: "Appelez-nous au {{practice.phone}} et nous vous aiderons à trouver une autre chambre.",
    noShowSubject: "Nous vous attendions — {{stay.ref}}",
    noShowHeading: "Nous vous attendions, {{recipient.first_name}}.",
    noShowPara: "Nous avons gardé votre chambre pour le {{stay.arrive.day_month}}, mais vous n'êtes pas arrivé : la réservation {{stay.ref}} est donc marquée comme no-show. Vous ne payez rien.",
    noShowRing: "Si vous êtes encore en route, appelez-nous au {{practice.phone}}.",
    datesName: "Dates modifiées",
    datesSubject: "Vos dates ont changé – {{stay.ref}}",
    datesPre: "Du {{stay.arrive.day_month}} au {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "Vos dates ont changé, {{recipient.first_name}}.",
    datesBefore: "Avant : du {{was.arrive.day_month}} au {{was.depart.day_month}}.",
    datesNow: "Maintenant : du {{stay.arrive.day_month}} au {{stay.depart.day_month}}. Vos extras suivent les nouvelles dates.",
    linkName: "Un nouveau lien",
    linkSubject: "Un nouveau lien vers votre réservation {{stay.ref}}",
    linkPre: "L'ancien lien ne l'ouvre plus",
    linkHeading: "Voici votre nouveau lien, {{recipient.first_name}}.",
    linkPara: "Vous avez demandé un nouveau lien vers votre réservation. Le lien que nous vous avions envoyé ne l'ouvre plus.",
    linkRing: "Si vous ne l'avez pas demandé, appelez-nous au {{practice.phone}}.",
    folioName: "La note du séjour",
    folioSubject: "Votre note du séjour de {{appName}} – {{stay.ref}}",
    folioPre: "Du {{stay.arrive.day_month}} au {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "Merci de votre séjour, {{recipient.first_name}}.",
    folioPara: "Nous espérons vous revoir bientôt.",
    soFarName: "La note du séjour à ce jour",
    soFarSubject: "Votre note du séjour à ce jour – {{stay.ref}}",
    soFarPre: "{{stay.balance.money}} restent à régler",
    soFarHeading: "Votre note du séjour à ce jour, {{recipient.first_name}}.",
    soFarPara: "Il reste {{stay.balance.money}} à régler à la réception.",
  },
);

export const EMAIL_DA = words(
  {
    reference: "Din reference",
    theRoom: "{{room_type.name}}, {{stay.arrive.day_month}} til {{stay.depart.day_month}}",
    total: "I alt",
    settle: "Der trækkes intet online. Du betaler i receptionen.",
    cancelBy: "Det koster intet at afbestille. Efter kl. {{stay.cancel_by.time}} den {{stay.cancel_by.date}} noteres en afbestilling som sen.",
    lateOrEarly: "Sent eller tidligt? Skriv til {{practice.email}}, eller ring til os på {{practice.phone}}.",
    totalWas: "I alt, før {{was.total.money}}",
    taxLine: "{{stay.tax_label}} ({{stay.tax_rate.percent}})",
    paid: "Betalt",
    balanceLine: "Mangler at betale",
    attached: "Din opholdsregning for {{room_type.name}}, {{stay.arrive.day_month}} til {{stay.depart.day_month}}, er vedhæftet.",
    foot: `${FOOT} Du får denne e-mail, fordi du har reserveret et værelse hos os.`,
  },
  {
    madeName: "Reservation modtaget",
    madeDeskName: "Reservation lavet i receptionen",
    madeSubject: "Dit værelse på {{appName}}, {{stay.ref}}",
    madePre: "{{stay.arrive.day_month}} til {{stay.depart.day_month}} · {{stay.total.money}} · der trækkes intet online",
    madeDeskPre: "{{stay.arrive.day_month}} til {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "Du har et værelse, {{recipient.first_name}}.",
    madePara: "Ankomst {{stay.arrive.day_month}} fra kl. {{practice.arrive_from.time}}. Afrejse {{stay.depart.day_month}} senest kl. {{practice.leave_by.time}}.",
    button: "Se din reservation",
    cancelledSubject: "Din reservation {{stay.ref}} er afbestilt",
    nothing: "Der opkræves intet.",
    cancelledHeading: "Din reservation er afbestilt.",
    stillOpen: "Hvis det ikke var meningen at afbestille, så skriv til {{practice.email}} eller ring til os på {{practice.phone}}, så ser vi, hvad der stadig er ledigt.",
    selfLate: "Du afbestilte efter kl. {{stay.cancel_by.time}} den {{stay.cancel_by.date}}, så den er markeret som en sen afbestilling. Der opkræves intet.",
    desk: "Som du bad om, har vi afbestilt den. Der opkræves intet.",
    deskLate: "Som du bad om, har vi afbestilt den. Det var efter kl. {{stay.cancel_by.time}} den {{stay.cancel_by.date}}, så den er markeret som en sen afbestilling. Der opkræves intet.",
    names: {
      self: "Afbestilt af gæsten",
      selfLate: "Afbestilt sent af gæsten",
      desk: "Afbestilt efter gæstens ønske",
      deskLate: "Afbestilt sent efter gæstens ønske",
      house: "Afbestilt af hotellet",
      noShow: "Vi savnede dig",
    },
    houseSubject: "Vi har måttet aflyse {{stay.ref}}",
    housePre: "Vi beklager meget · der opkræves intet",
    houseHeading: "Vi beklager meget, {{recipient.first_name}}.",
    housePara: "Vi har måttet aflyse din reservation {{stay.ref}} ({{room_type.name}}, {{stay.arrive.day_month}} til {{stay.depart.day_month}}). Vi beklager meget. Der opkræves intet.",
    houseRing: "Ring til os på {{practice.phone}}, så hjælper vi dig med at finde et andet værelse.",
    noShowSubject: "Vi savnede dig — {{stay.ref}}",
    noShowHeading: "Vi savnede dig, {{recipient.first_name}}.",
    noShowPara: "Vi holdt dit værelse til den {{stay.arrive.day_month}}, men du kom ikke, så reservation {{stay.ref}} er markeret som udeblevet. Der opkræves intet.",
    noShowRing: "Hvis du stadig er på vej, så ring til os på {{practice.phone}}.",
    datesName: "Datoer ændret",
    datesSubject: "Dine datoer er ændret – {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} til {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "Dine datoer er ændret, {{recipient.first_name}}.",
    datesBefore: "Før: {{was.arrive.day_month}} til {{was.depart.day_month}}.",
    datesNow: "Nu: {{stay.arrive.day_month}} til {{stay.depart.day_month}}. Dine tilvalg følger de nye datoer.",
    linkName: "Et nyt link",
    linkSubject: "Et nyt link til din reservation {{stay.ref}}",
    linkPre: "Det gamle link åbner den ikke længere",
    linkHeading: "Her er dit nye link, {{recipient.first_name}}.",
    linkPara: "Du har bedt om et nyt link til din reservation. Det link, vi sendte før, åbner den ikke længere.",
    linkRing: "Hvis du ikke har bedt om det, så ring til os på {{practice.phone}}.",
    folioName: "Opholdsregningen",
    folioSubject: "Din opholdsregning fra {{appName}} – {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} til {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "Tak fordi du boede hos os, {{recipient.first_name}}.",
    folioPara: "Vi håber at se dig igen.",
    soFarName: "Opholdsregningen indtil nu",
    soFarSubject: "Din opholdsregning indtil nu – {{stay.ref}}",
    soFarPre: "{{stay.balance.money}} mangler at blive betalt",
    soFarHeading: "Din opholdsregning indtil nu, {{recipient.first_name}}.",
    soFarPara: "Der mangler {{stay.balance.money}} at blive betalt i receptionen.",
  },
);

export const EMAIL_CS = words(
  {
    reference: "Číslo vaší rezervace",
    theRoom: "{{room_type.name}}, {{stay.arrive.day_month}} až {{stay.depart.day_month}}",
    total: "Celkem",
    settle: "Online se nic nestrhává. Platíte na recepci.",
    cancelBy: "Zrušení nic nestojí. Po {{stay.cancel_by.time}} dne {{stay.cancel_by.date}} se zrušení zaznamená jako pozdní.",
    lateOrEarly: "Přijedete později nebo dříve? Napište na {{practice.email}} nebo nám zavolejte na {{practice.phone}}.",
    totalWas: "Celkem, dříve {{was.total.money}}",
    taxLine: "{{stay.tax_label}} ({{stay.tax_rate.percent}})",
    paid: "Zaplaceno",
    balanceLine: "Zbývá zaplatit",
    attached: "V příloze posíláme účet pobytu za {{room_type.name}}, {{stay.arrive.day_month}} až {{stay.depart.day_month}}.",
    foot: `${FOOT} Tento e-mail dostáváte, protože jste si u nás rezervovali pokoj.`,
  },
  {
    madeName: "Rezervace vytvořena",
    madeDeskName: "Rezervace na recepci",
    madeSubject: "Váš pokoj v {{appName}}, {{stay.ref}}",
    madePre: "{{stay.arrive.day_month}} až {{stay.depart.day_month}} · {{stay.total.money}} · online se nic nestrhává",
    madeDeskPre: "{{stay.arrive.day_month}} až {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "Pokoj je váš, {{recipient.first_name}}.",
    madePara: "Příjezd {{stay.arrive.day_month}} od {{practice.arrive_from.time}}. Odjezd {{stay.depart.day_month}} do {{practice.leave_by.time}}.",
    button: "Zobrazit rezervaci",
    cancelledSubject: "Vaše rezervace {{stay.ref}} je zrušena",
    nothing: "Nic se neúčtuje.",
    cancelledHeading: "Vaše rezervace je zrušena.",
    stillOpen: "Pokud jste rušit nechtěli, napište na {{practice.email}} nebo nám zavolejte na {{practice.phone}} a podíváme se, co je ještě volné.",
    selfLate: "Zrušili jste po {{stay.cancel_by.time}} dne {{stay.cancel_by.date}}, proto je zrušení označeno jako pozdní. Nic se neúčtuje.",
    desk: "Na vaši žádost jsme ji zrušili. Nic se neúčtuje.",
    deskLate: "Na vaši žádost jsme ji zrušili. Bylo to po {{stay.cancel_by.time}} dne {{stay.cancel_by.date}}, proto je zrušení označeno jako pozdní. Nic se neúčtuje.",
    names: {
      self: "Zrušeno hostem",
      selfLate: "Zrušeno hostem pozdě",
      desk: "Zrušeno na přání hosta",
      deskLate: "Zrušeno na přání hosta pozdě",
      house: "Zrušeno hotelem",
      noShow: "Chyběli jste nám",
    },
    houseSubject: "Museli jsme zrušit {{stay.ref}}",
    housePre: "Velmi se omlouváme · nic se neúčtuje",
    houseHeading: "Velmi se omlouváme, {{recipient.first_name}}.",
    housePara: "Museli jsme zrušit vaši rezervaci {{stay.ref}} ({{room_type.name}}, {{stay.arrive.day_month}} až {{stay.depart.day_month}}). Velmi se omlouváme. Nic se neúčtuje.",
    houseRing: "Zavolejte nám na {{practice.phone}} a pomůžeme vám najít jiný pokoj.",
    noShowSubject: "Chyběli jste nám — {{stay.ref}}",
    noShowHeading: "Chyběli jste nám, {{recipient.first_name}}.",
    noShowPara: "Drželi jsme vám pokoj na {{stay.arrive.day_month}}, ale nedorazili jste, proto je rezervace {{stay.ref}} označena jako nedostavení se. Nic se neúčtuje.",
    noShowRing: "Pokud jste ještě na cestě, zavolejte nám na {{practice.phone}}.",
    datesName: "Termín změněn",
    datesSubject: "Termín vašeho pobytu se změnil – {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} až {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "Termín vašeho pobytu se změnil, {{recipient.first_name}}.",
    datesBefore: "Dříve: {{was.arrive.day_month}} až {{was.depart.day_month}}.",
    datesNow: "Nyní: {{stay.arrive.day_month}} až {{stay.depart.day_month}}. Vaše doplňky platí pro nový termín.",
    linkName: "Nový odkaz",
    linkSubject: "Nový odkaz na vaši rezervaci {{stay.ref}}",
    linkPre: "Starý odkaz ji už neotevře",
    linkHeading: "Tady je váš nový odkaz, {{recipient.first_name}}.",
    linkPara: "Požádali jste o nový odkaz na svou rezervaci. Odkaz, který jsme vám poslali dříve, ji už neotevře.",
    linkRing: "Pokud jste o něj nežádali, zavolejte nám na {{practice.phone}}.",
    folioName: "Účet pobytu",
    folioSubject: "Váš účet pobytu z {{appName}} – {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} až {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "Děkujeme za váš pobyt, {{recipient.first_name}}.",
    folioPara: "Budeme se těšit na další shledání.",
    soFarName: "Průběžný účet pobytu",
    soFarSubject: "Váš dosavadní účet pobytu – {{stay.ref}}",
    soFarPre: "Zbývá zaplatit {{stay.balance.money}}",
    soFarHeading: "Váš dosavadní účet pobytu, {{recipient.first_name}}.",
    soFarPara: "Na recepci zbývá zaplatit {{stay.balance.money}}.",
  },
);

export const EMAIL_AR = words(
  {
    reference: "رقم حجزك",
    theRoom: "{{room_type.name}}، من {{stay.arrive.day_month}} إلى {{stay.depart.day_month}}",
    total: "الإجمالي",
    settle: "لا يُقتطع أي مبلغ عبر الإنترنت. تدفع في مكتب الاستقبال.",
    cancelBy: "الإلغاء لا يكلّف شيئًا. بعد {{stay.cancel_by.time}} يوم {{stay.cancel_by.date}} يُسجَّل الإلغاء على أنه متأخر.",
    lateOrEarly: "ستتأخر أو تصل مبكرًا؟ راسلنا على {{practice.email}} أو اتصل بنا على {{practice.phone}}.",
    totalWas: "الإجمالي، وكان {{was.total.money}}",
    taxLine: "{{stay.tax_label}} ({{stay.tax_rate.percent}})",
    paid: "المدفوع",
    balanceLine: "المتبقي للسداد",
    attached: "مرفق حساب إقامتك لـ {{room_type.name}}، من {{stay.arrive.day_month}} إلى {{stay.depart.day_month}}.",
    foot: `${FOOT} تصلك هذه الرسالة لأنك حجزت غرفة لدينا.`,
  },
  {
    madeName: "تم الحجز",
    madeDeskName: "حجز من الاستقبال",
    madeSubject: "غرفتك في {{appName}}، {{stay.ref}}",
    madePre: "من {{stay.arrive.day_month}} إلى {{stay.depart.day_month}} · {{stay.total.money}} · لا يُقتطع شيء عبر الإنترنت",
    madeDeskPre: "من {{stay.arrive.day_month}} إلى {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "غرفتك محجوزة يا {{recipient.first_name}}.",
    madePara: "الوصول في {{stay.arrive.day_month}} ابتداءً من {{practice.arrive_from.time}}. المغادرة في {{stay.depart.day_month}} قبل {{practice.leave_by.time}}.",
    button: "عرض حجزك",
    cancelledSubject: "أُلغي حجزك {{stay.ref}}",
    nothing: "لا يُحتسب أي مبلغ.",
    cancelledHeading: "أُلغي حجزك.",
    stillOpen: "إن لم تكن تقصد الإلغاء، فراسلنا على {{practice.email}} أو اتصل بنا على {{practice.phone}} وسنرى ما لا يزال متاحًا.",
    selfLate: "ألغيت بعد {{stay.cancel_by.time}} يوم {{stay.cancel_by.date}}، لذا سُجّل الإلغاء على أنه متأخر. لا يُحتسب أي مبلغ.",
    desk: "ألغيناه كما طلبت. لا يُحتسب أي مبلغ.",
    deskLate: "ألغيناه كما طلبت. كان ذلك بعد {{stay.cancel_by.time}} يوم {{stay.cancel_by.date}}، لذا سُجّل الإلغاء على أنه متأخر. لا يُحتسب أي مبلغ.",
    names: {
      self: "ألغاه الضيف",
      selfLate: "ألغاه الضيف متأخرًا",
      desk: "أُلغي بطلب من الضيف",
      deskLate: "أُلغي بطلب من الضيف متأخرًا",
      house: "ألغاه الفندق",
      noShow: "كنا بانتظارك",
    },
    houseSubject: "اضطررنا إلى إلغاء {{stay.ref}}",
    housePre: "نعتذر كثيرًا · لا يُحتسب أي مبلغ",
    houseHeading: "نعتذر كثيرًا يا {{recipient.first_name}}.",
    housePara: "اضطررنا إلى إلغاء حجزك {{stay.ref}} ({{room_type.name}}، من {{stay.arrive.day_month}} إلى {{stay.depart.day_month}}). نعتذر كثيرًا. لا يُحتسب أي مبلغ.",
    houseRing: "اتصل بنا على {{practice.phone}} وسنساعدك في إيجاد غرفة أخرى.",
    noShowSubject: "كنا بانتظارك — {{stay.ref}}",
    noShowHeading: "كنا بانتظارك يا {{recipient.first_name}}.",
    noShowPara: "احتفظنا بغرفتك ليوم {{stay.arrive.day_month}} لكنك لم تصل، لذا سُجّل الحجز {{stay.ref}} على أنه عدم حضور. لا يُحتسب أي مبلغ.",
    noShowRing: "إن كنت لا تزال في الطريق، فاتصل بنا على {{practice.phone}}.",
    datesName: "تغيّرت التواريخ",
    datesSubject: "تغيّرت تواريخ إقامتك — {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} إلى {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "تغيّرت تواريخ إقامتك يا {{recipient.first_name}}.",
    datesBefore: "سابقًا: {{was.arrive.day_month}} إلى {{was.depart.day_month}}.",
    datesNow: "الآن: {{stay.arrive.day_month}} إلى {{stay.depart.day_month}}. إضافاتك تتبع التواريخ الجديدة.",
    linkName: "رابط جديد",
    linkSubject: "رابط جديد لحجزك {{stay.ref}}",
    linkPre: "لم يعد الرابط القديم يفتحه",
    linkHeading: "إليك رابطك الجديد يا {{recipient.first_name}}.",
    linkPara: "طلبت رابطًا جديدًا لحجزك. الرابط الذي أرسلناه سابقًا لم يعد يفتحه.",
    linkRing: "إن لم تطلبه، اتصل بنا على {{practice.phone}}.",
    folioName: "حساب الإقامة",
    folioSubject: "حساب إقامتك من {{appName}} — {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} إلى {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "شكرًا لإقامتك معنا يا {{recipient.first_name}}.",
    folioPara: "نأمل أن نراك مجددًا.",
    soFarName: "حساب الإقامة حتى الآن",
    soFarSubject: "حساب إقامتك حتى الآن — {{stay.ref}}",
    soFarPre: "{{stay.balance.money}} متبقية للسداد",
    soFarHeading: "حساب إقامتك حتى الآن يا {{recipient.first_name}}.",
    soFarPara: "يتبقى {{stay.balance.money}} للسداد في الاستقبال.",
  },
);

export const EMAIL_ZH_CN = words(
  {
    reference: "您的预订号",
    theRoom: "{{room_type.name}}，{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}",
    total: "总计",
    settle: "网上不收取任何费用，请在前台结清。",
    cancelBy: "取消不收取任何费用。{{stay.cancel_by.date}} {{stay.cancel_by.time}} 之后取消，将记为逾期取消。",
    lateOrEarly: "会晚到或早到？请发邮件至 {{practice.email}} 或致电 {{practice.phone}}。",
    totalWas: "总计（原为 {{was.total.money}}）",
    taxLine: "{{stay.tax_label}}（{{stay.tax_rate.percent}}）",
    paid: "已付",
    balanceLine: "待结清",
    attached: "附件是您入住{{room_type.name}}（{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}）的住宿结算单。",
    foot: "{{appName}} · {{practice.address}} · {{practice.phone}} · {{practice.email}}。您收到此邮件，是因为您在我们这里预订了房间。",
  },
  {
    madeName: "预订成功",
    madeDeskName: "前台预订",
    madeSubject: "您在 {{appName}} 的房间，{{stay.ref}}",
    madePre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}} · 网上不收取费用",
    madeDeskPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "{{recipient.first_name}}，您的房间已订好。",
    madePara: "{{stay.arrive.day_month}} 入住，{{practice.arrive_from.time}} 起可办理。{{stay.depart.day_month}} 退房，请于 {{practice.leave_by.time}} 前离开。",
    button: "查看您的预订",
    cancelledSubject: "您的预订 {{stay.ref}} 已取消",
    nothing: "不收取任何费用。",
    cancelledHeading: "您的预订已取消。",
    stillOpen: "如果您并非有意取消，请发邮件至 {{practice.email}} 或致电 {{practice.phone}}，我们会看看还有哪些房间。",
    selfLate: "您在 {{stay.cancel_by.date}} {{stay.cancel_by.time}} 之后取消，因此记为逾期取消。不收取任何费用。",
    desk: "已按您的要求取消。不收取任何费用。",
    deskLate: "已按您的要求取消。取消时间在 {{stay.cancel_by.date}} {{stay.cancel_by.time}} 之后，因此记为逾期取消。不收取任何费用。",
    names: { self: "客人取消", selfLate: "客人逾期取消", desk: "应客人要求取消", deskLate: "应客人要求逾期取消", house: "酒店取消", noShow: "未能等到您" },
    houseSubject: "我们不得不取消 {{stay.ref}}",
    housePre: "非常抱歉 · 不收取任何费用",
    houseHeading: "{{recipient.first_name}}，非常抱歉。",
    housePara: "我们不得不取消您的预订 {{stay.ref}}（{{room_type.name}}，{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}）。非常抱歉。不收取任何费用。",
    houseRing: "请致电 {{practice.phone}}，我们会帮您另找房间。",
    noShowSubject: "我们未能等到您 — {{stay.ref}}",
    noShowHeading: "{{recipient.first_name}}，我们没能等到您。",
    noShowPara: "我们为您保留了 {{stay.arrive.day_month}} 的房间，但您没有到店，因此预订 {{stay.ref}} 记为未到店。不收取任何费用。",
    noShowRing: "如果您仍在路上，请致电 {{practice.phone}}。",
    datesName: "日期已更改",
    datesSubject: "您的入住日期已更改 — {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "{{recipient.first_name}}，您的入住日期已更改。",
    datesBefore: "更改前：{{was.arrive.day_month}} 至 {{was.depart.day_month}}。",
    datesNow: "现在：{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}。您的附加项目随新日期调整。",
    linkName: "新链接",
    linkSubject: "您的预订 {{stay.ref}} 的新链接",
    linkPre: "旧链接已无法打开",
    linkHeading: "{{recipient.first_name}}，这是您的新链接。",
    linkPara: "您申请了预订的新链接。我们之前发送的链接已无法打开该预订。",
    linkRing: "如果不是您本人申请，请致电 {{practice.phone}}。",
    folioName: "住宿结算单",
    folioSubject: "您在{{appName}}的住宿结算单 — {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "{{recipient.first_name}}，感谢您的入住。",
    folioPara: "期待再次见到您。",
    soFarName: "目前的住宿结算单",
    soFarSubject: "您目前的住宿结算单 — {{stay.ref}}",
    soFarPre: "待结清 {{stay.balance.money}}",
    soFarHeading: "{{recipient.first_name}}，这是您目前的住宿结算单。",
    soFarPara: "尚有 {{stay.balance.money}} 需在前台结清。",
  },
);

export const EMAIL_ZH_TW = words(
  {
    reference: "訂房編號",
    theRoom: "{{room_type.name}}，{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}",
    total: "總計",
    settle: "線上不收取任何費用，請在櫃檯結清。",
    cancelBy: "取消不收取任何費用。{{stay.cancel_by.date}} {{stay.cancel_by.time}} 之後取消，將記為逾期取消。",
    lateOrEarly: "會晚到或早到？請寄信至 {{practice.email}} 或來電 {{practice.phone}}。",
    totalWas: "總計（原為 {{was.total.money}}）",
    taxLine: "{{stay.tax_label}}（{{stay.tax_rate.percent}}）",
    paid: "已付",
    balanceLine: "待結清",
    attached: "附件是您入住{{room_type.name}}（{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}）的住宿結算單。",
    foot: "{{appName}} · {{practice.address}} · {{practice.phone}} · {{practice.email}}。您收到這封郵件，是因為您在我們這裡預訂了房間。",
  },
  {
    madeName: "預訂成功",
    madeDeskName: "櫃檯預訂",
    madeSubject: "您在 {{appName}} 的房間，{{stay.ref}}",
    madePre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}} · 線上不收取費用",
    madeDeskPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    madeHeading: "{{recipient.first_name}}，您的房間已訂好。",
    madePara: "{{stay.arrive.day_month}} 入住，{{practice.arrive_from.time}} 起可辦理。{{stay.depart.day_month}} 退房，請於 {{practice.leave_by.time}} 前離開。",
    button: "查看您的訂房",
    cancelledSubject: "您的預訂 {{stay.ref}} 已取消",
    nothing: "不收取任何費用。",
    cancelledHeading: "您的預訂已取消。",
    stillOpen: "如果您並非有意取消，請寄信至 {{practice.email}} 或來電 {{practice.phone}}，我們會看看還有哪些房間。",
    selfLate: "您在 {{stay.cancel_by.date}} {{stay.cancel_by.time}} 之後取消，因此記為逾期取消。不收取任何費用。",
    desk: "已依您的要求取消。不收取任何費用。",
    deskLate: "已依您的要求取消。取消時間在 {{stay.cancel_by.date}} {{stay.cancel_by.time}} 之後，因此記為逾期取消。不收取任何費用。",
    names: { self: "客人取消", selfLate: "客人逾期取消", desk: "應客人要求取消", deskLate: "應客人要求逾期取消", house: "飯店取消", noShow: "我們沒等到您" },
    houseSubject: "我們不得不取消 {{stay.ref}}",
    housePre: "非常抱歉 · 不收取任何費用",
    houseHeading: "{{recipient.first_name}}，非常抱歉。",
    housePara: "我們不得不取消您的預訂 {{stay.ref}}（{{room_type.name}}，{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}）。非常抱歉。不收取任何費用。",
    houseRing: "請來電 {{practice.phone}}，我們會幫您另找房間。",
    noShowSubject: "我們沒等到您 — {{stay.ref}}",
    noShowHeading: "{{recipient.first_name}}，我們沒等到您。",
    noShowPara: "我們為您保留了 {{stay.arrive.day_month}} 的房間，但您沒有到店，因此預訂 {{stay.ref}} 記為未到店。不收取任何費用。",
    noShowRing: "如果您仍在路上，請來電 {{practice.phone}}。",
    datesName: "日期已變更",
    datesSubject: "您的入住日期已變更 — {{stay.ref}}",
    datesPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    datesHeading: "{{recipient.first_name}}，您的入住日期已變更。",
    datesBefore: "變更前：{{was.arrive.day_month}} 至 {{was.depart.day_month}}。",
    datesNow: "現在：{{stay.arrive.day_month}} 至 {{stay.depart.day_month}}。您的加購項目會跟著新日期調整。",
    linkName: "新連結",
    linkSubject: "您的預訂 {{stay.ref}} 的新連結",
    linkPre: "舊連結已無法開啟",
    linkHeading: "{{recipient.first_name}}，這是您的新連結。",
    linkPara: "您申請了預訂的新連結。我們先前寄出的連結已無法開啟該預訂。",
    linkRing: "如果不是您本人申請，請致電 {{practice.phone}}。",
    folioName: "住宿結算單",
    folioSubject: "您在{{appName}}的住宿結算單 — {{stay.ref}}",
    folioPre: "{{stay.arrive.day_month}} 至 {{stay.depart.day_month}} · {{stay.total.money}}",
    folioHeading: "{{recipient.first_name}}，感謝您的入住。",
    folioPara: "期待再次見到您。",
    soFarName: "目前的住宿結算單",
    soFarSubject: "您目前的住宿結算單 — {{stay.ref}}",
    soFarPre: "待結清 {{stay.balance.money}}",
    soFarHeading: "{{recipient.first_name}}，這是您目前的住宿結算單。",
    soFarPara: "尚有 {{stay.balance.money}} 需在櫃檯結清。",
  },
);
