/**
 * The manifest's labels in the seven languages beside English, keyed by the
 * English label (see `labels.ts`).
 *
 * EVERY ENTRY IS AN UNREVIEWED DRAFT until a native speaker has read it (the
 * release waits for that review). The drafts keep to the product's words: a
 * cancellation is "at no charge", never "free" in any language, and a better
 * room at the booked price is never an "upgrade" — `manifest-lexicon.test.ts`
 * reads every one of them against each language's list.
 */
import type { Translation } from "./labels.ts";

/** One label's seven: German, French, Danish, Czech, Arabic, Simplified and Traditional Chinese. */
const w = (de: string, fr: string, da: string, cs: string, ar: string, zhCN: string, zhTW: string): Translation => ({
  "de-DE": de,
  "fr-FR": fr,
  "da-DK": da,
  "cs-CZ": cs,
  "ar-EG": ar,
  "zh-CN": zhCN,
  "zh-TW": zhTW,
});

export const WORDS: Record<string, Translation> = {
  "A later email took its place": w("Eine spätere E-Mail hat sie ersetzt", "Un e-mail plus récent l'a remplacé", "En senere e-mail erstattede den", "Nahradil ho pozdější e-mail", "حلّ محلها بريد لاحق", "已被之后的邮件取代", "已被之後的郵件取代"),
  "A night": w("Pro Nacht", "Par nuit", "Pr. nat", "Za noc", "لليلة", "每晚", "每晚"),
  "A night they missed": w("Eine versäumte Nacht", "Une nuit manquée", "En nat de ikke kom", "Zmeškaná noc", "ليلة لم يحضروها", "未入住的一晚", "未入住的一晚"),
  "About line": w("Kurzbeschreibung", "Phrase d'accueil", "Kort om huset", "Úvodní věta", "سطر تعريفي", "简介", "簡介"),
  Added: w("Hinzugefügt", "Ajouté", "Tilføjet", "Přidáno", "أُضيف", "添加时间", "新增時間"),
  "Added a night": w("Aufschlag pro Nacht", "Ajout par nuit", "Tillæg pr. nat", "Příplatek za noc", "إضافة لكل ليلة", "每晚加价", "每晚加價"),
  Address: w("Adresse", "Adresse", "Adresse", "Adresa", "العنوان", "地址", "地址"),
  Amount: w("Betrag", "Montant", "Beløb", "Částka", "المبلغ", "金额", "金額"),
  "Arrive from": w("Anreise ab", "Arrivée à partir de", "Ankomst fra", "Příjezd od", "الوصول من", "最早入住", "最早入住"),
  Arriving: w("Anreise", "Arrivée", "Ankomst", "Příjezd", "الوصول", "入住", "入住"),
  "Arriving about": w("Ankunft gegen", "Arrivée vers", "Ankommer omkring", "Přijede kolem", "الوصول نحو", "预计到达", "預計抵達"),
  "Arriving today": w("Anreise heute", "Arrivées du jour", "Ankommer i dag", "Přijíždějí dnes", "الواصلون اليوم", "今日入住", "今日入住"),
  "At the desk": w("An der Rezeption", "À la réception", "I receptionen", "Na recepci", "في الاستقبال", "前台", "櫃檯"),
  "Before tax": w("Vor Steuern", "Hors taxes", "Før skat", "Před zdaněním", "قبل الضريبة", "税前", "稅前"),
  "Being cleaned": w("Wird gereinigt", "En nettoyage", "Bliver gjort rent", "Uklízí se", "قيد التنظيف", "清洁中", "清潔中"),
  Booked: w("Gebucht", "Réservé", "Booket", "Rezervováno", "محجوز", "已预订", "已預訂"),
  "Breakfast hours": w("Frühstückszeiten", "Horaires du petit-déjeuner", "Morgenmadstider", "Doba snídaně", "مواعيد الإفطار", "早餐时间", "早餐時間"),
  "By car": w("Mit dem Auto", "En voiture", "I bil", "Autem", "بالسيارة", "自驾", "開車"),
  "By train": w("Mit dem Zug", "En train", "Med tog", "Vlakem", "بالقطار", "乘火车", "搭火車"),
  "Cancel at no charge until": w("Stornierung ohne Kosten bis", "Annulation sans frais jusqu'au", "Afbestilling uden beregning indtil", "Zrušení bez poplatku do", "الإلغاء دون رسوم حتى", "此前取消不收费", "此前取消不收費"),
  Cancelled: w("Storniert", "Annulé", "Afbestilt", "Zrušeno", "ملغى", "已取消", "已取消"),
  "Cancelled at the guest's request": w("Auf Wunsch des Gastes storniert", "Annulé à la demande du client", "Afbestilt efter gæstens ønske", "Zrušeno na přání hosta", "أُلغي بطلب من الضيف", "应客人要求取消", "應客人要求取消"),
  "Cancelled at the guest's request, late": w("Auf Wunsch des Gastes spät storniert", "Annulé tardivement à la demande du client", "Afbestilt sent efter gæstens ønske", "Zrušeno na přání hosta pozdě", "أُلغي بطلب من الضيف متأخرًا", "应客人要求逾期取消", "應客人要求逾期取消"),
  "Cancelled by": w("Storniert von", "Annulé par", "Afbestilt af", "Zrušil", "ألغاه", "取消人", "取消人"),
  "Cancelled by the guest": w("Vom Gast storniert", "Annulé par le client", "Afbestilt af gæsten", "Zrušeno hostem", "ألغاه الضيف", "客人取消", "客人取消"),
  "Cancelled by the guest, late": w("Vom Gast spät storniert", "Annulé tardivement par le client", "Afbestilt sent af gæsten", "Zrušeno hostem pozdě", "ألغاه الضيف متأخرًا", "客人逾期取消", "客人逾期取消"),
  "Cancelled by the house": w("Vom Haus storniert", "Annulé par l'hôtel", "Afbestilt af huset", "Zrušeno hotelem", "ألغاه الفندق", "酒店取消", "飯店取消"),
  Card: w("Karte", "Carte", "Kort", "Karta", "بطاقة", "银行卡", "信用卡"),
  Cash: w("Bar", "Espèces", "Kontant", "Hotově", "نقدًا", "现金", "現金"),
  Charge: w("Posten", "Consommation", "Postering", "Položka", "رسم", "费用", "費用"),
  "Charge item": w("Artikel", "Article", "Vare", "Položka nabídky", "بند", "收费项目", "收費項目"),
  "Charge items": w("Artikel", "Articles", "Varer", "Položky nabídky", "البنود", "收费项目", "收費項目"),
  Charged: w("Berechnet", "Compté", "Beregnet", "Účtováno", "يُحتسب", "收取方式", "收取方式"),
  "Charged on": w("Berechnet am", "Ajouté le", "Tilføjet den", "Přidáno dne", "أُضيف في", "记入日期", "記入日期"),
  Charges: w("Posten", "Consommations", "Posteringer", "Položky", "الرسوم", "费用", "費用"),
  "Checked in": w("Eingecheckt", "Arrivé", "Tjekket ind", "Ubytován", "تم تسجيل الدخول", "已入住", "已入住"),
  "Checked in by": w("Eingecheckt von", "Accueilli par", "Tjekket ind af", "Ubytoval", "سجّل الدخول", "办理入住人", "辦理入住人"),
  "Checked out": w("Ausgecheckt", "Parti", "Tjekket ud", "Odhlášen", "تم تسجيل المغادرة", "已退房", "已退房"),
  "Checked out by": w("Ausgecheckt von", "Départ enregistré par", "Tjekket ud af", "Odhlásil", "سجّل المغادرة", "办理退房人", "辦理退房人"),
  Code: w("Kürzel", "Code", "Kode", "Kód", "الرمز", "代码", "代碼"),
  Colour: w("Farbe", "Couleur", "Farve", "Barva", "اللون", "颜色", "顏色"),
  Counted: w("Angerechnet", "Compté", "Medregnet", "Započteno", "المحتسب", "计入", "計入"),
  Created: w("Erstellt", "Créé", "Oprettet", "Vytvořeno", "أُنشئ", "创建时间", "建立時間"),
  "Days ahead a guest may reserve": w("Tage im Voraus buchbar", "Jours de réservation à l'avance", "Dage frem en gæst kan reservere", "Kolik dní předem lze rezervovat", "عدد الأيام المتاحة للحجز مسبقًا", "可提前预订天数", "可提前預訂天數"),
  "Days' notice to cancel": w("Tage Frist zum Stornieren", "Délai d'annulation (jours)", "Dages varsel for afbestilling", "Dní předem na zrušení", "أيام الإشعار للإلغاء", "取消需提前天数", "取消需提前天數"),
  Description: w("Beschreibung", "Description", "Beskrivelse", "Popis", "الوصف", "描述", "描述"),
  Detail: w("Detail", "Détail", "Detalje", "Podrobnost", "التفاصيل", "说明", "說明"),
  "Details deleted": w("Daten gelöscht", "Données supprimées", "Oplysninger slettet", "Údaje smazány", "حُذفت البيانات", "资料已删除", "資料已刪除"),
  Dropped: w("Abgewählt", "Retiré", "Fravalgt", "Odebráno", "أُزيل", "已移除", "已移除"),
  Due: w("Versand ab", "À envoyer le", "Sendes", "Odeslat", "موعد الإرسال", "发送时间", "寄送時間"),
  Email: w("E-Mail", "E-mail", "E-mail", "E-mail", "البريد الإلكتروني", "电子邮件", "電子郵件"),
  "Email guests": w("Gäste per E-Mail benachrichtigen", "Envoyer des e-mails aux clients", "Send e-mail til gæster", "Posílat hostům e-maily", "مراسلة الضيوف بالبريد", "给客人发邮件", "寄郵件給客人"),
  Emails: w("E-Mails", "E-mails", "E-mails", "E-maily", "رسائل البريد", "邮件", "郵件"),
  Expected: w("Erwartet", "Attendu", "Forventet", "Očekáván", "متوقع", "预计到达", "預計抵達"),
  Extra: w("Extra", "Extra", "Tilvalg", "Doplněk", "إضافة", "附加项目", "附加項目"),
  "Extra on a stay": w("Extra zum Aufenthalt", "Extra du séjour", "Tilvalg på et ophold", "Doplněk pobytu", "إضافة على الإقامة", "住宿附加项目", "住宿附加項目"),
  Extras: w("Extras", "Extras", "Tilvalg", "Doplňky", "الإضافات", "附加项目", "附加項目"),
  "Extras a night": w("Extras pro Nacht", "Extras par nuit", "Tilvalg pr. nat", "Doplňky za noc", "الإضافات لكل ليلة", "每晚附加费用", "每晚附加費用"),
  "Extras on stays": w("Extras der Aufenthalte", "Extras des séjours", "Tilvalg på ophold", "Doplňky pobytů", "إضافات الإقامات", "住宿附加项目", "住宿附加項目"),
  Feature: w("Ausstattung", "Équipement", "Facilitet", "Vybavení", "ميزة", "设施", "設施"),
  Features: w("Ausstattung", "Équipements", "Faciliteter", "Vybavení", "المزايا", "设施", "設施"),
  "Finding us": w("Anfahrt", "Nous trouver", "Find vej", "Jak nás najít", "كيف تصل إلينا", "如何找到我们", "如何找到我們"),
  "First name": w("Vorname", "Prénom", "Fornavn", "Jméno", "الاسم الأول", "名", "名"),
  "First night": w("Erste Nacht", "Première nuit", "Første nat", "První noc", "الليلة الأولى", "首晚", "首晚"),
  "First reference number": w("Erste Referenznummer", "Premier numéro de référence", "Første referencenummer", "První číslo rezervace", "رقم المرجع الأول", "起始参考号", "起始參考號"),
  "First stay": w("Erster Aufenthalt", "Premier séjour", "Første ophold", "První pobyt", "الإقامة الأولى", "首次入住", "首次入住"),
  Floor: w("Etage", "Étage", "Etage", "Patro", "الطابق", "楼层", "樓層"),
  Folio: w("Folio", "Note du séjour", "Folio", "Účet pobytu", "كشف الحساب", "消费明细", "消費明細"),
  "Folio and receipts": w("Folio und Belege", "Note du séjour et reçus", "Folio og kvitteringer", "Účet pobytu a stvrzenky", "كشف الحساب والإيصالات", "消费明细与收据", "消費明細與收據"),
  From: w("Von", "Du", "Fra", "Od", "من", "从", "從"),
  "Given back": w("Zurückgegeben", "Rendu", "Givet tilbage", "Vráceno", "مُعاد", "已退还", "已退還"),
  "Going out": w("Wird gesendet", "En cours d'envoi", "Sendes", "Odesílá se", "قيد الإرسال", "发送中", "寄送中"),
  Guest: w("Gast", "Client", "Gæst", "Host", "ضيف", "客人", "客人"),
  "Guest account": w("Gastkonto", "Compte client", "Gæstekonto", "Účet hosta", "حساب الضيف", "客人账户", "客人帳戶"),
  Guests: w("Gäste", "Voyageurs", "Gæster", "Hosté", "الضيوف", "客人", "客人"),
  "House note": w("Hausinfo", "Info de la maison", "Husnote", "Poznámka domu", "ملاحظة المنزل", "住宿须知", "住宿須知"),
  "House notes": w("Hausinfos", "Infos de la maison", "Husnoter", "Poznámky domu", "ملاحظات المنزل", "住宿须知", "住宿須知"),
  "House settings": w("Hauseinstellungen", "Réglages de la maison", "Husindstillinger", "Nastavení domu", "إعدادات الفندق", "酒店设置", "飯店設定"),
  How: w("Wie", "Moyen", "Hvordan", "Způsob", "الطريقة", "方式", "方式"),
  "How it is charged": w("Wie es berechnet wird", "Mode de calcul", "Sådan beregnes det", "Jak se účtuje", "طريقة الاحتساب", "收取方式说明", "收取方式說明"),
  Icon: w("Symbol", "Icône", "Ikon", "Ikona", "أيقونة", "图标", "圖示"),
  "In house": w("Im Haus", "Présent", "I huset", "Ubytován", "مقيم", "在住", "在住"),
  "In house now": w("Jetzt im Haus", "Présents", "I huset nu", "Nyní ubytovaní", "المقيمون الآن", "当前在住", "目前在住"),
  Item: w("Artikel", "Article", "Vare", "Položka", "البند", "项目", "項目"),
  Kind: w("Art", "Type", "Type", "Druh", "النوع", "类型", "類型"),
  Language: w("Sprache", "Langue", "Sprog", "Jazyk", "اللغة", "语言", "語言"),
  "Last night": w("Letzte Nacht", "Dernière nuit", "Sidste nat", "Poslední noc", "الليلة الأخيرة", "末晚", "末晚"),
  "Last night out": w("Letzte Nacht außer Betrieb", "Dernière nuit hors service", "Sidste nat ude af drift", "Poslední noc mimo provoz", "آخر ليلة خارج الخدمة", "停用至（含当晚）", "停用至（含當晚）"),
  "Late arrival words": w("Text für späte Anreise", "Texte d'arrivée tardive", "Tekst ved sen ankomst", "Text pro pozdní příjezd", "نص الوصول المتأخر", "晚到说明", "晚到說明"),
  "Late cancellation": w("Späte Stornierung", "Annulation tardive", "Sen afbestilling", "Pozdní zrušení", "إلغاء متأخر", "逾期取消", "逾期取消"),
  "Late cancellations this month": w("Späte Stornierungen diesen Monat", "Annulations tardives ce mois-ci", "Sene afbestillinger denne måned", "Pozdní zrušení tento měsíc", "الإلغاءات المتأخرة هذا الشهر", "本月逾期取消", "本月逾期取消"),
  "Late leaving until": w("Später Check-out bis", "Départ tardif jusqu'à", "Sen afrejse indtil", "Pozdní odjezd do", "المغادرة المتأخرة حتى", "延迟退房至", "延遲退房至"),
  "Leave by": w("Abreise bis", "Départ avant", "Afrejse senest", "Odjezd do", "المغادرة قبل", "最晚退房", "最晚退房"),
  Leaving: w("Abreise", "Départ", "Afrejse", "Odjezd", "المغادرة", "退房", "退房"),
  "Leaving today": w("Abreise heute", "Départs du jour", "Rejser i dag", "Odjíždějí dnes", "المغادرون اليوم", "今日退房", "今日退房"),
  "Left early": w("Früher abgereist", "Parti plus tôt", "Rejste før tid", "Odjel dříve", "غادر مبكرًا", "提前离开", "提前離開"),
  "Link code": w("Link-Code", "Code du lien", "Linkkode", "Kód odkazu", "رمز الرابط", "链接代码", "連結代碼"),
  "Link stopped": w("Link gestoppt", "Lien désactivé", "Link stoppet", "Odkaz zastaven", "الرابط متوقف", "链接已停用", "連結已停用"),
  "Longest stay (nights)": w("Längster Aufenthalt (Nächte)", "Séjour le plus long (nuits)", "Længste ophold (nætter)", "Nejdelší pobyt (noci)", "أطول إقامة (ليالٍ)", "最长入住（晚）", "最長入住（晚）"),
  Made: w("Gebucht", "Réservé", "Oprettet", "Vytvořeno", "أُجري", "预订时间", "預訂時間"),
  Manage: w("Verwalten", "Gérer", "Administrer", "Správa", "الإدارة", "管理", "管理"),
  "Marked as a no-show": w("Als nicht erschienen markiert", "Marqué non présenté", "Markeret som udeblevet", "Označen jako nedostavení", "سُجّل عدم الحضور", "标记为未到店", "標記為未到店"),
  Messages: w("Nachrichten", "Messages", "Beskeder", "Zprávy", "الرسائل", "消息", "訊息"),
  Mobile: w("Mobil", "Portable", "Mobil", "Mobil", "الجوال", "手机", "手機"),
  "Money recorded this month": w("Diesen Monat erfasste Zahlungen", "Encaissements du mois", "Betalinger registreret denne måned", "Platby zaznamenané tento měsíc", "المبالغ المسجلة هذا الشهر", "本月记录款项", "本月記錄款項"),
  Name: w("Name", "Nom", "Navn", "Název", "الاسم", "名称", "名稱"),
  Nights: w("Nächte", "Nuits", "Nætter", "Noci", "الليالي", "晚数", "晚數"),
  "Nights not stayed": w("Nicht genutzte Nächte", "Nuits non effectuées", "Nætter ikke brugt", "Nevyužité noci", "ليالٍ لم تُقضَ", "未入住的夜晚", "未入住的夜晚"),
  "Nights of the week": w("Wochentage (Nächte)", "Nuits de la semaine", "Ugedage (nætter)", "Noci v týdnu", "ليالي الأسبوع", "适用星期", "適用星期"),
  "No longer needed": w("Nicht mehr nötig", "Plus nécessaire", "Ikke længere nødvendig", "Již není potřeba", "لم يعد مطلوبًا", "不再需要", "不再需要"),
  "No-show": w("Nicht erschienen", "Non présenté", "Udeblevet", "Nedostavil se", "لم يحضر", "未到店", "未到店"),
  "No-show time": w("Uhrzeit für Nichterscheinen", "Heure de non-présentation", "Tidspunkt for udeblivelse", "Čas nedostavení", "وقت عدم الحضور", "未到店判定时间", "未到店判定時間"),
  "No-shows this month": w("Nicht erschienen diesen Monat", "Non-présentations ce mois-ci", "Udeblivelser denne måned", "Nedostavení tento měsíc", "حالات عدم الحضور هذا الشهر", "本月未到店", "本月未到店"),
  "Not sent": w("Nicht gesendet", "Non envoyé", "Ikke sendt", "Neodesláno", "لم يُرسل", "未发送", "未寄出"),
  Note: w("Notiz", "Note", "Note", "Poznámka", "ملاحظة", "备注", "備註"),
  "Note from the guest": w("Notiz des Gastes", "Mot du client", "Note fra gæsten", "Poznámka hosta", "ملاحظة الضيف", "客人备注", "客人備註"),
  Number: w("Nummer", "Numéro", "Nummer", "Číslo", "الرقم", "房号", "房號"),
  Occupied: w("Belegt", "Occupée", "Optaget", "Obsazeno", "مشغولة", "已入住", "已入住"),
  Offered: w("Angeboten", "Proposé", "Tilbydes", "Nabízeno", "معروض", "提供中", "提供中"),
  On: w("Aktiv", "Actif", "Aktiv", "Aktivní", "مفعّل", "启用", "啟用"),
  "On foot": w("Zu Fuß", "À pied", "Til fods", "Pěšky", "سيرًا على الأقدام", "步行", "步行"),
  "On guests' accounts": w("Offen auf Gästekonten", "Sur les comptes des clients", "På gæsternes konti", "Na účtech hostů", "على حسابات الضيوف", "客人账上未付", "客人帳上未付"),
  "On the folio": w("Auf dem Folio", "Sur la note", "På folioen", "Na účtu pobytu", "في كشف الحساب", "明细金额", "明細金額"),
  "On the stay": w("Beim Aufenthalt", "Sur le séjour", "På opholdet", "U pobytu", "ضمن الإقامة", "已加入", "已加入"),
  "Once a stay": w("Einmal pro Aufenthalt", "Une fois par séjour", "Én gang pr. ophold", "Jednou za pobyt", "مرة لكل إقامة", "每次入住一次", "每次入住一次"),
  Online: w("Online", "En ligne", "Online", "Online", "عبر الإنترنت", "网上", "線上"),
  "Out of service": w("Außer Betrieb", "Hors service", "Ude af drift", "Mimo provoz", "خارج الخدمة", "停用", "停用"),
  Overview: w("Übersicht", "Vue d'ensemble", "Overblik", "Přehled", "نظرة عامة", "概览", "總覽"),
  Owing: w("Offen", "Reste dû", "Udestående", "Zbývá doplatit", "المستحق", "待付", "待付"),
  Paid: w("Bezahlt", "Payé", "Betalt", "Zaplaceno", "المدفوع", "已付", "已付"),
  Payment: w("Zahlung", "Paiement", "Betaling", "Platba", "دفعة", "付款", "付款"),
  Payments: w("Zahlungen", "Paiements", "Betalinger", "Platby", "المدفوعات", "付款", "付款"),
  "Per night": w("Pro Nacht", "Par nuit", "Pr. nat", "Za noc", "لكل ليلة", "每晚", "每晚"),
  "Per person, per night": w("Pro Person und Nacht", "Par personne et par nuit", "Pr. person pr. nat", "Za osobu a noc", "لكل شخص في الليلة", "每人每晚", "每人每晚"),
  Phone: w("Telefon", "Téléphone", "Telefon", "Telefon", "الهاتف", "电话", "電話"),
  Position: w("Reihenfolge", "Ordre", "Rækkefølge", "Pořadí", "الترتيب", "排序", "排序"),
  Price: w("Preis", "Prix", "Pris", "Cena", "السعر", "价格", "價格"),
  "Print a guest's folio at the desk and email it at check-out, with a receipt for each payment.": w(
    "Das Folio eines Gastes an der Rezeption drucken und beim Check-out per E-Mail senden, mit einem Beleg für jede Zahlung.",
    "Imprimer la note d'un client à la réception et l'envoyer par e-mail au départ, avec un reçu pour chaque paiement.",
    "Udskriv en gæsts folio i receptionen, og send den på e-mail ved udtjekning, med en kvittering for hver betaling.",
    "Vytisknout účet pobytu hosta na recepci a poslat ho e-mailem při odjezdu, se stvrzenkou ke každé platbě.",
    "اطبع كشف حساب الضيف في الاستقبال وأرسله بالبريد عند المغادرة، مع إيصال لكل دفعة.",
    "在前台打印客人的消费明细，退房时通过邮件发送，并为每笔付款附上收据。",
    "在櫃檯列印客人的消費明細，退房時以郵件寄出，並為每筆付款附上收據。",
  ),
  "Rate a night": w("Preis pro Nacht", "Prix par nuit", "Pris pr. nat", "Cena za noc", "سعر الليلة", "每晚房价", "每晚房價"),
  "Rate rule": w("Preisregel", "Règle de prix", "Prisregel", "Cenové pravidlo", "قاعدة سعر", "房价规则", "房價規則"),
  "Rate rules": w("Preisregeln", "Règles de prix", "Prisregler", "Cenová pravidla", "قواعد الأسعار", "房价规则", "房價規則"),
  Ready: w("Bereit", "Prête", "Klar", "Připraveno", "جاهزة", "可入住", "可入住"),
  Reason: w("Grund", "Motif", "Årsag", "Důvod", "السبب", "原因", "原因"),
  Receipt: w("Beleg", "Reçu", "Kvittering", "Stvrzenka", "إيصال", "收据", "收據"),
  Recorded: w("Erfasst", "Enregistré", "Registreret", "Zaznamenáno", "سُجّل", "记录时间", "記錄時間"),
  "Recorded by": w("Erfasst von", "Enregistré par", "Registreret af", "Zaznamenal", "سجّله", "记录人", "記錄人"),
  Records: w("Einträge", "Registres", "Poster", "Záznamy", "السجلات", "记录", "紀錄"),
  Reference: w("Referenz", "Référence", "Reference", "Číslo rezervace", "المرجع", "参考号", "參考號"),
  "Reference (running)": w("Referenz (laufend)", "Référence (séquence)", "Reference (løbende)", "Pořadové číslo", "المرجع (متسلسل)", "参考号（流水）", "參考號（流水）"),
  "Reference prefix": w("Referenz-Präfix", "Préfixe de référence", "Referencepræfiks", "Předpona čísla", "بادئة المرجع", "参考号前缀", "參考號前綴"),
  Reservation: w("Reservierung", "Réservation", "Reservation", "Rezervace", "حجز", "预订", "預訂"),
  "Reservation made": w("Reservierung eingegangen", "Réservation effectuée", "Reservation modtaget", "Rezervace vytvořena", "تم الحجز", "预订成功", "預訂成功"),
  "Reservation made at the desk": w("Reservierung an der Rezeption", "Réservation faite à la réception", "Reservation lavet i receptionen", "Rezervace na recepci", "حجز من الاستقبال", "前台预订", "櫃檯預訂"),
  Reservations: w("Reservierungen", "Réservations", "Reservationer", "Rezervace", "الحجوزات", "预订", "預訂"),
  "Reservations made each week": w("Reservierungen pro Woche", "Réservations par semaine", "Reservationer pr. uge", "Rezervace za týden", "الحجوزات كل أسبوع", "每周预订量", "每週預訂量"),
  "Retry key": w("Wiederholungsschlüssel", "Clé de nouvel essai", "Genforsøgsnøgle", "Klíč opakování", "مفتاح إعادة المحاولة", "重试键", "重試鍵"),
  Room: w("Zimmer", "Chambre", "Værelse", "Pokoj", "الغرفة", "房间", "房間"),
  "Room type": w("Zimmerart", "Type de chambre", "Værelsestype", "Typ pokoje", "نوع الغرفة", "房型", "房型"),
  "Room types": w("Zimmerarten", "Types de chambre", "Værelsestyper", "Typy pokojů", "أنواع الغرف", "房型", "房型"),
  Rooms: w("Zimmer", "Chambres", "Værelser", "Pokoje", "الغرف", "房间", "房間"),
  "Same as the extra": w("Entspricht dem Extra", "Correspond à l'extra", "Samme som tilvalget", "Odpovídá doplňku", "مطابق للإضافة", "对应附加项目", "對應附加項目"),
  Sent: w("Gesendet", "Envoyé", "Sendt", "Odesláno", "أُرسل", "已发送", "已寄出"),
  "Set by": w("Eingetragen von", "Saisi par", "Sat af", "Zadal", "حدّده", "设置人", "設定人"),
  "Set on": w("Eingetragen am", "Saisi le", "Sat den", "Zadáno", "حُدّد في", "设置时间", "設定時間"),
  Settings: w("Einstellungen", "Réglages", "Indstillinger", "Nastavení", "الإعدادات", "设置", "設定"),
  "Short line": w("Kurzzeile", "Accroche", "Kort linje", "Krátký popis", "سطر قصير", "一句话介绍", "一句話介紹"),
  "Short name": w("Kurzname", "Nom court", "Kort navn", "Krátký název", "الاسم المختصر", "简称", "簡稱"),
  Since: w("Seit", "Depuis", "Siden", "Od roku", "منذ", "创立于", "創立於"),
  Skipped: w("Übersprungen", "Ignoré", "Sprunget over", "Přeskočeno", "تم تخطيه", "已跳过", "已略過"),
  "Skipped by hand": w("Von Hand übersprungen", "Ignoré à la main", "Sprunget over manuelt", "Přeskočeno ručně", "تُخطّي يدويًا", "手动跳过", "手動略過"),
  Sleeps: w("Schlafplätze", "Couchages", "Sovepladser", "Lůžka", "يتسع لـ", "可住人数", "可住人數"),
  "Spaces a night": w("Plätze pro Nacht", "Places par nuit", "Pladser pr. nat", "Míst za noc", "أماكن لكل ليلة", "每晚车位", "每晚車位"),
  Status: w("Status", "Statut", "Status", "Stav", "الحالة", "状态", "狀態"),
  Surname: w("Nachname", "Nom", "Efternavn", "Příjmení", "اسم العائلة", "姓", "姓"),
  Taken: w("Erhalten", "Encaissé", "Modtaget", "Přijato", "مستلم", "已收", "已收"),
  Tax: w("Steuer", "Taxe", "Skat", "Daň", "الضريبة", "税费", "稅費"),
  "Tax name": w("Steuerbezeichnung", "Nom de la taxe", "Skattens navn", "Název daně", "اسم الضريبة", "税费名称", "稅費名稱"),
  "Tax rate (%)": w("Steuersatz (%)", "Taux de taxe (%)", "Skattesats (%)", "Sazba daně (%)", "نسبة الضريبة (%)", "税率（%）", "稅率（%）"),
  "The guest asked the desk": w("Der Gast hat an der Rezeption gefragt", "Le client l'a demandé à la réception", "Gæsten bad receptionen", "Host požádal recepci", "طلب الضيف من الاستقبال", "客人向前台提出", "客人向櫃檯提出"),
  "The guest, online": w("Der Gast, online", "Le client, en ligne", "Gæsten, online", "Host, online", "الضيف، عبر الإنترنت", "客人（网上）", "客人（線上）"),
  "The house": w("Das Haus", "L'hôtel", "Huset", "Hotel", "الفندق", "酒店", "飯店"),
  "The morning": w("Der Morgen", "Le matin", "Morgenen", "Ráno", "الصباح", "早晨", "早晨"),
  To: w("An", "À", "Til", "Komu", "إلى", "收件人", "收件人"),
  Total: w("Gesamt", "Total", "I alt", "Celkem", "الإجمالي", "总计", "總計"),
  Town: w("Ort", "Ville", "By", "Obec", "البلدة", "城镇", "城鎮"),
  Transfer: w("Überweisung", "Virement", "Overførsel", "Převod", "تحويل", "转账", "轉帳"),
  Until: w("Bis", "Jusqu'au", "Indtil", "Do", "حتى", "至", "至"),
  Void: w("Storniert", "Annulé", "Annulleret", "Zrušeno", "ملغى", "作废", "作廢"),
  Voided: w("Storniert", "Annulé", "Annulleret", "Zrušeno", "ملغى", "已作废", "已作廢"),
  "Voided by": w("Storniert von", "Annulé par", "Annulleret af", "Zrušil", "ألغاه", "作废人", "作廢人"),
  "Voided on": w("Storniert am", "Annulé le", "Annulleret den", "Zrušeno dne", "أُلغي في", "作废时间", "作廢時間"),
  "We missed you": w("Wir haben Sie vermisst", "Vous nous avez manqué", "Vi savnede dig", "Chyběli jste nám", "افتقدناك", "我们错过了您", "我們錯過了您"),
  "What went wrong": w("Was schiefging", "Ce qui n'a pas fonctionné", "Hvad gik galt", "Co se pokazilo", "ما الخطأ", "出错原因", "出錯原因"),
  "Who cancelled": w("Wer storniert hat", "Qui a annulé", "Hvem afbestilte", "Kdo zrušil", "من ألغى", "取消方", "取消方"),
  Why: w("Warum", "Pourquoi", "Hvorfor", "Proč", "السبب", "原因", "原因"),
  "Why it was skipped": w("Warum übersprungen", "Motif de l'omission", "Hvorfor sprunget over", "Proč přeskočeno", "سبب التخطي", "跳过原因", "略過原因"),
  "Why it was voided": w("Warum storniert", "Motif d'annulation", "Hvorfor annulleret", "Proč zrušeno", "سبب الإلغاء", "作废原因", "作廢原因"),
};
