/**
 * The icons the house's screens draw, by their Lucide names. Named imports, so only these ship;
 * a name the house typed that is not here (an extra's or a note's icon) draws a plain circle.
 */
import {
  AppWindow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Ban,
  Bath,
  Bed,
  BedDouble,
  BedSingle,
  Beer,
  Bell,
  Bird,
  BookOpen,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  Car,
  CarFront,
  Check,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  ClockAlert,
  Coffee,
  ConciergeBell,
  Croissant,
  Dog,
  DoorClosed,
  DoorOpen,
  Ellipsis,
  FileX,
  Footprints,
  Grid3x3,
  House,
  Info,
  KeyRound,
  LampDesk,
  Languages,
  LayoutDashboard,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailOpen,
  MapPin,
  Menu,
  MonitorSmartphone,
  Moon,
  NotebookPen,
  Pencil,
  PencilLine,
  Phone,
  Plus,
  Printer,
  ReceiptText,
  RotateCcw,
  Sandwich,
  Search,
  ShieldCheck,
  Shirt,
  ShowerHead,
  Sofa,
  Sparkles,
  SprayCan,
  SquarePen,
  Sun,
  Sunrise,
  Tag,
  TrainFront,
  Trash2,
  Trees,
  TriangleAlert,
  Undo2,
  Unplug,
  UserRound,
  UserX,
  Wallet,
  Waves,
  Wifi,
  WifiOff,
  Wine,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "app-window": AppWindow,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "ban": Ban,
  "bath": Bath,
  "bed": Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  "beer": Beer,
  "bell": Bell,
  "bird": Bird,
  "book-open": BookOpen,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  "calendar-search": CalendarSearch,
  "calendar-x": CalendarX,
  "car": Car,
  "car-front": CarFront,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "clock": Clock,
  "clock-alert": ClockAlert,
  "coffee": Coffee,
  "concierge-bell": ConciergeBell,
  "croissant": Croissant,
  "dog": Dog,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  "ellipsis": Ellipsis,
  "file-x": FileX,
  "footprints": Footprints,
  "grid-3x3": Grid3x3,
  "house": House,
  "info": Info,
  "key-round": KeyRound,
  "lamp-desk": LampDesk,
  "languages": Languages,
  "layout-dashboard": LayoutDashboard,
  "link": Link,
  "list": List,
  "loader-circle": LoaderCircle,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "mail-open": MailOpen,
  "map-pin": MapPin,
  "menu": Menu,
  "monitor-smartphone": MonitorSmartphone,
  "moon": Moon,
  "notebook-pen": NotebookPen,
  "pencil": Pencil,
  "pencil-line": PencilLine,
  "phone": Phone,
  "plus": Plus,
  "printer": Printer,
  "receipt-text": ReceiptText,
  "rotate-ccw": RotateCcw,
  "sandwich": Sandwich,
  "search": Search,
  "shield-check": ShieldCheck,
  "shirt": Shirt,
  "shower-head": ShowerHead,
  "sofa": Sofa,
  "sparkles": Sparkles,
  "spray-can": SprayCan,
  "square-pen": SquarePen,
  "sun": Sun,
  "sunrise": Sunrise,
  "tag": Tag,
  "train-front": TrainFront,
  "trash-2": Trash2,
  "trees": Trees,
  "triangle-alert": TriangleAlert,
  "undo-2": Undo2,
  "unplug": Unplug,
  "user-round": UserRound,
  "user-x": UserX,
  "wallet": Wallet,
  "waves": Waves,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "wine": Wine,
  "wrench": Wrench,
  "x": X,
};
